name: lessonReserve
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          # MYSQL_ROOT_PASSWORD - root superuser password
          mysql root password: hs456789
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: lessonReserve
          # MYSQL_USER - create the specified user with superuser power for created database
          mysql user: hs
          # MYSQL_PASSWORD - specified superuser password which user is power for created database
          mysql password: hs456789
          

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      - name: Generate deployment package
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }} #환경변수
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }} #환경변수
          application_name: lessonReserve # 엘리스틱 빈스톡 애플리케이션 이름!
          environment_name: lessonReserve-env # 엘리스틱 빈스톡 환경 이름!
          version_label: lessonReserve-${{steps.current-time.outputs.formattedTime}} # 버전 시간
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
